CREATE TABLE `USER` (
  `USER_ID` int NOT NULL,
  `USERNAME` varchar(100) NOT NULL,
  `PASSWORD` varchar(50) NOT NULL,
  `USER_ROLE` char(1) DEFAULT 'C',
  `USER_STATUS` char(1) DEFAULT NULL,
  `FIRSTNAME` varchar(100) DEFAULT NULL,
  `LASTNAME` varchar(100) DEFAULT NULL,
  `DOB DATETIME DEFAULT NULL,
  `ADD_LINE1` varchar(255) DEFAULT NULL,
  `ADD_LINE2` varchar(255) DEFAULT NULL,
  `CITY` varchar(50) DEFAULT NULL,
  `STATE` varchar(50) DEFAULT NULL,
  `PIN` int(6) DEFAULT NULL,
  `MOBILE_NUMBER` int(10) DEFAULT NULL,
  `EMAIL_ID` varchar(100) DEFAULT NULL,
  `AADHAR_ID` int(16) DEFAULT NULL,
  `PAN` varchar(10) DEFAULT NULL,
   PRIMARY KEY (`USER_ID`)
)



